/**
 * File upload / download routes.
 *
 * Storage policy:
 *   - New uploads are stored via storeContent() — S3 first (when enabled),
 *     local fallback on any error or when S3 is disabled.
 *   - Every new upload record is saved to the `uploaded_files` Mongo
 *     collection so reads can be routed correctly regardless of where the
 *     file physically lives.
 *   - Legacy files that pre-date this metadata collection are served
 *     directly from the local uploads directory (fallback path).
 *
 * URL shape is unchanged: /api/files/:filename
 */
import { Router, type Request, type Response } from 'express';
import { existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import { randomUUID } from 'node:crypto';
import multer from 'multer';
import type { Db, Collection } from 'mongodb';
import {
  getUploadsDir,
  ensureLocalDir,
  storeContent,
  readStoredContent,
  type StorageProvider,
} from '../services/upload-storage.js';

// ── Metadata collection ───────────────────────────────────────────────────

interface UploadedFileDoc {
  /** Stored filename (UUID + ext) — used as the lookup key. */
  fileId: string;
  originalName: string;
  size: number;
  mimeType: string;
  storageProvider: StorageProvider;
  /** Absolute local path — set when storageProvider === 'local'. */
  localPath?: string;
  /** S3 object key — set when storageProvider === 's3'. */
  s3Key?: string;
  /** S3 bucket name — set when storageProvider === 's3'. */
  s3Bucket?: string;
  createdAt: Date;
}

function filesCol(db: Db): Collection<UploadedFileDoc> {
  return db.collection<UploadedFileDoc>('uploaded_files');
}

// ── Multer disk storage (local) ───────────────────────────────────────────
//
// Multer always writes to the local uploads directory first.  When S3 is
// enabled we upload the on-disk file to S3 in the route handler and record
// the S3 location in metadata.  This two-step approach lets multer handle
// streaming + validation while keeping S3 as an optional backend.

const storage = multer.diskStorage({
  destination: (_req, _file, cb) => {
    const dir = getUploadsDir();
    ensureLocalDir(dir);
    cb(null, dir);
  },
  filename: (_req, file, cb) => {
    const id = randomUUID();
    const ext = extname(file.originalname);
    cb(null, `${id}${ext}`);
  },
});

const upload = multer({
  storage,
  limits: { fileSize: 50 * 1024 * 1024 }, // 50 MB
});

// ── Public file-download router ───────────────────────────────────────────
//
// Intentionally NOT behind `requireAuth`. Mounted BEFORE the global auth
// middleware in app.ts so that links to uploaded files (generated by the
// `upload_file` agent tool and shared in chat / Slack) are clickable
// without a session. Filenames are cryptographically random UUIDs so
// possession of the link is the access control — same pattern as a signed URL.
//
// Write operations are NOT exposed here — they go through `fileRoutes()`
// which IS auth-gated.

export function publicFileRoutes(db: Db): Router {
  const router = Router();

  // GET /api/files/:filename — serve a file publicly.
  router.get('/:filename', async (req: Request, res: Response) => {
    const filename = Array.isArray(req.params.filename)
      ? req.params.filename[0]
      : req.params.filename;
    if (filename.includes('..') || filename.includes('/')) {
      return res.status(400).json({ error: 'Invalid filename' });
    }

    try {
      // ── 1. Try metadata-driven read (new files and S3 files) ──
      const meta = await filesCol(db).findOne({ fileId: filename });
      if (meta) {
        if (meta.storageProvider === 's3') {
          // Stream S3 content directly — can't use sendFile for remote objects.
          const content = await readStoredContent({
            provider: 's3',
            s3Key: meta.s3Key,
            s3Bucket: meta.s3Bucket,
          });
          res.setHeader('Content-Length', String(content.length));
          return res.end(content);
        }
        // Local metadata record — use sendFile for efficient streaming.
        const localPath = meta.localPath ?? join(getUploadsDir(), filename);
        if (!existsSync(localPath)) {
          return res.status(404).json({ error: 'File not found' });
        }
        return res.sendFile(localPath);
      }

      // ── 2. Legacy fallback: serve from local uploads directory ──
      const filePath = join(getUploadsDir(), filename);
      if (!existsSync(filePath)) {
        return res.status(404).json({ error: 'File not found' });
      }
      res.sendFile(filePath);
    } catch (err: unknown) {
      res.status(500).json({ error: (err as Error).message });
    }
  });

  return router;
}

// ── Auth-gated file upload router ─────────────────────────────────────────
//
// Mounted AFTER `requireAuth` in app.ts. Only authenticated users and
// agents can create files.

export function fileRoutes(db: Db): Router {
  const router = Router();

  // POST /api/files — upload a file, returns public URL
  router.post('/', upload.single('file'), async (req: Request, res: Response) => {
    const file = req.file;
    if (!file) return res.status(400).json({ error: 'No file uploaded' });

    const filename = file.filename;
    const localPath = file.path; // absolute path written by multer

    try {
      // Attempt S3 upload of the already-written local file
      const { readFileSync } = await import('node:fs');
      const fileContent = readFileSync(localPath);
      const location = await storeContent({
        localPath,
        s3Key: `files/${filename}`,
        content: fileContent,
        contentType: file.mimetype,
      });

      await filesCol(db).insertOne({
        fileId: filename,
        originalName: file.originalname,
        size: file.size,
        mimeType: file.mimetype,
        storageProvider: location.provider,
        localPath: location.localPath,
        s3Key: location.s3Key,
        s3Bucket: location.s3Bucket,
        createdAt: new Date(),
      });

      res.status(201).json({
        filename,
        originalName: file.originalname,
        size: file.size,
        mimeType: file.mimetype,
        url: `/api/files/${filename}`,
      });
    } catch (err: unknown) {
      res.status(500).json({ error: (err as Error).message });
    }
  });

  // POST /api/files/from-content — create a file from text content (used by agents/MCP)
  router.post('/from-content', async (req: Request, res: Response) => {
    const { content, filename: requestedName, mimeType } = req.body as {
      content?: string;
      filename?: string;
      mimeType?: string;
    };
    if (!content || !requestedName) {
      return res.status(400).json({ error: 'content and filename are required' });
    }

    const id = randomUUID();
    const ext = extname(requestedName);
    const storedName = `${id}${ext}`;
    const localPath = join(getUploadsDir(), storedName);

    try {
      const location = await storeContent({
        localPath,
        s3Key: `files/${storedName}`,
        content,
        contentType: mimeType ?? 'text/plain',
      });

      const size = Buffer.byteLength(content, 'utf-8');

      await filesCol(db).insertOne({
        fileId: storedName,
        originalName: requestedName,
        size,
        mimeType: mimeType ?? 'text/plain',
        storageProvider: location.provider,
        localPath: location.localPath,
        s3Key: location.s3Key,
        s3Bucket: location.s3Bucket,
        createdAt: new Date(),
      });

      res.status(201).json({
        filename: storedName,
        originalName: requestedName,
        size,
        mimeType: mimeType ?? 'text/plain',
        url: `/api/files/${storedName}`,
      });
    } catch (err: unknown) {
      res.status(500).json({ error: (err as Error).message });
    }
  });

  return router;
}
